version: '3'

services:
  app:
    build:
      context: node
    networks: 
     - node-network
    volumes:
      - ./node:/usr/src/app
    tty: true
    container_name: app
    ports:
      - "3000:3000"
    entrypoint: wait-for db:3306 -t 40 -- node index.js
    depends_on:
      - db

  db:
    image: mysql:5.7
    platform: linux/amd64
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks: 
     - node-network

  nginx:
    build:
      context: nginx
    ports:
      - "8080:80"
    networks: 
     - node-network


networks:
  node-network:
    driver: bridge